# Generated by Django 4.1.7 on 2023-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32)),
                ('city_ascii', models.CharField(max_length=32)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('country', models.CharField(max_length=32)),
                ('iso2', models.CharField(max_length=32)),
                ('iso3', models.CharField(max_length=32)),
                ('admin_name', models.CharField(max_length=32)),
                ('population', models.IntegerField(null=True)),
                ('cityid', models.IntegerField(null=True)),
            ],
        ),
    ]
