# Generated by Django 4.1.7 on 2023-04-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
