# Generated by Django 4.1.7 on 2023-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='city_ascii',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='timezone',
            field=models.IntegerField(default=0),
        ),
    ]
